repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-build
        args: [-race]
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
# - repo: local
#   hooks:
#     - id: embed
#       name: embed
#       entry: >
#         go run github.com/romnn/embedme/cmd/embedme --verify README.md
#
#       language: system
#       pass_filenames: false
